# Api available at http://api_francaise:8000

version: "3"

services:
    web:
        container_name: api_francaise
        build: ./
        # Uncomment the next line to use the local version of the api
        #ports:
        #    - "8000:8000"
        networks:
            - api_francaise

    db:
        image: mariadb
        container_name: db
        restart: always
        volumes:
            - ./bd/database.sql:/docker-entrypoint-initdb.d/init.sql
            - db_data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - api_francaise

volumes:
    db_data:

networks:
    api_francaise:
