name: Unit Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3
      - name: Building docker
        run: docker-compose up --build -d
      - name: Sleep for 30 seconds to wait for MySQL
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Check running containers
        run: docker ps
      - name: Run unit tests
        run: docker exec api-francaises-des-dev-api pytest

  