name: Unit Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3
      - name: Building docker
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          down-flags: "--volumes"
      - name: Run unit tests
        uses: addnab/docker-run-action@v3
        with:
          image: 'Dockerfile'
          run: pytest

  