name: Unit Test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MYSQL_USER: api
  MYSQL_PASSWORD: api
  MYSQL_DATABASE: API_francaises_des_dev
  MYSQL_PORT: 32001
  MYSQL_HOST: localhost

jobs:
  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo 
        uses: actions/checkout@v3
      - name: Starting MySQL docker
        run: docker-compose up -d api-francaises-des-dev-mysql
      - name: Sleep for 30 seconds to wait for MySQL
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run unit tests
        run: |
          pytest

  